DataMigrationBundle\Entity\DataMigration:
  type: mappedSuperclass
  table: ars_data_migration
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    label:
      type: string
      length: 255
      nullable: true
      unique: true
    executed:
      type: boolean
